### ISSUE TITLE
Meteor 1.3 System js

### ISSUE THREAD

**Issue by Markusxmr** [TsumiNa/meteor-systemjs#2]
Greetings,
I was wandering, since Meteor recently introduced ES2015 module support, would it be practical to use systemjs installed directly from npm within a meteor app, since it is now possible. Thus, for example Meteor-Aurelia could have a more "standard" usage?

**Comment by TsumiNa** [comment]
Yes, I know here is a issue with systemjs. also since 1.3 we can use module loader and npm modules directly.

I'm checking but need more times :bow: 

if everything by use npm installation works great. I will close this package :smile:

**Comment by Markusxmr** [comment]
:v:

**Comment by stphdenis** [comment]
It is due to an incompatibility between meteor v1.3 and systemjs as shown here https://github.com/meteor/meteor/issues/6046 and I made a pull request for a patch in systemjs there https://github.com/systemjs/systemjs/pull/980

**Comment by TsumiNa** [comment]
@stphdenis thank you! this troubled me a lot but i don't know a lot about systemjs. keep tracking this

**Comment by stphdenis** [comment]
The commits were done in the systemejs project.
Could you give us a new release of `TsumiNa/meteor-systemjs` ?

**Comment by TsumiNa** [comment]
@stphdenis Yes，I will do it as soon as possible.

**Comment by TsumiNa** [comment]
@stphdenis There is another issue with systemjs@>0.19.9. It will cause a `Cross origin requests` error.

```
XMLHttpRequest cannot load npm://aurelia-bootstrapper@1.0.0-beta.1.0.2/aurelia-bootstrapper.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

I updated this repo to use systemjs@0.19.17 so you can clone it and repr it locally.

**Comment by TsumiNa** [comment]
@Markusxmr I tried to use aurelia directly from node_modules. Because of the needed of load _.html files, there must be a plugin to handle how to do it. either systemjs or webpack will use a syntax like `_.html!text` to invoke a loader plugin but not in meteor. So this package will continue to update.

**Comment by Markusxmr** [comment]
Yes, sir. 
Ok, appreciated. Will close the issue for now.

**Comment by stphdenis** [comment]
To use aurelia directly from `node_modules`, there is a new module there [sdenis:aurelia](https://atmospherejs.com/sdenis/aurelia). It explains how to do with the new native `Meteor Aurelia loader`.

**Comment by Markusxmr** [comment]
@stphdenis nice one. will check it out. How was it working for you?

**Comment by ninzy3** [comment]
@TsumiNa 

How did you updated systemjs@0.19.17. My current version is systemjs@0.19.36.  I am getting the same error as

system.src.js:1057XMLHttpRequest cannot load file:///D:/Aurelia%20Program/minimal/jspm_packages/npm/aurelia-bootstrapper@1.0.0.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
